### ISSUE TITLE
Customizing look of swagger?

### ISSUE THREAD

**Issue by SimonDKnight** [ruby-grape/grape-swagger-rails#56]
Hi, I need to brand swagger so that it fits in with the organisation I am working for. How do I go about doing this without forking the gem?

Thanks

**Comment by aschuster3** [comment]
Hey @SimonDKnight, this is already marked as an issue in #27, so I'm going to close this one as a duplicate, but so that you're aware of progress on that one, I have a local branch that I'll probably push up sometime in the near future as a test branch that boxes the `<head>` and `<body>` elements in respective `content_for` statements, allowing for essentially white-labeling if you're using layouts.

Alternatively, if you take a look in issue #27, one of the comments offers a workaround so that you don't have to depend on me to release that test branch.

**Comment by SimonDKnight** [comment]
Thank you for your fast reply.
